Vagrant.configure(2) do |config|
  config.vm.box = 'debian-9-amd64'
  config.vm.hostname = 'example'
  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
end
