Vagrant.configure(2) do |config|
  config.vm.box = 'debian-9-amd64'

  config.vm.hostname = 'example'

  config.vm.provider 'libvirt' do |lv, config|
    lv.memory = 2048
    lv.cpus = 2
    lv.cpu_mode = 'host-passthrough'
    lv.nested = true
    lv.keymap = 'pt'
    config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provider 'vmware_esxi' do |esxi, config|
    esxi.esxi_hostname = '10.2.0.198'
    esxi.esxi_username = 'root'
    esxi.esxi_password = 'HeyH0Password'
    esxi.esxi_disk_store = 'datastore1'
    esxi.esxi_virtual_network = ['VM Network']
    esxi.guest_memsize = 2048
    esxi.guest_numvcpus = 2
  end

  config.vm.provision 'shell', inline: 'cat /etc/os-release', name: 'os-release'
  config.vm.provision 'shell', inline: 'cat /etc/debian_version', name: 'debian_version'
  config.vm.provision 'shell', inline: 'lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL', name: 'block devices'
  config.vm.provision 'shell', inline: 'df -h', name: 'disk space usage'
end
